"""
This file contains constants for the code
"""

VOXEL_SIZE = 0.05

VERTICAL_NORMAL_MIN_AREA = 1

FLOOR_MAX_HEIGHT = 5

MIN_WALL_AREA = 2
MIN_WALL_SEGMENT_VOLUME = 0.5
RANSAC_PLANE_DISTANCE_THRESHOLD = 2

OBJECT_CLUSTER_EPS = 2.01
OBJECT_CLUSTER_MIN_PTS = 10

OBJECT_POLYGONS_ALPHA = 0.2
